      $dialog.fsbox config -bg #a18fff
      $dialog.fsbox.bf config -bg #a18fff
      $dialog.fsbox.bf.cancel config -bg #816fff
      $dialog.fsbox.bf.cancel config -activebackground #ff00ae
      $dialog.fsbox.bf.cancel config -highlightthickness 0
      $dialog.fsbox.bf.hidden config -bg #a18fff
      $dialog.fsbox.bf.hidden config -activebackground #a18fff
      $dialog.fsbox.bf.hidden config -highlightthickness 0
      $dialog.fsbox.bf.ok config -bg #816fff
      $dialog.fsbox.bf.ok config -activebackground #ff00ae
      $dialog.fsbox.bf.ok config -highlightthickness 0
      $dialog.fsbox.lf config -bg #a18fff 
      $dialog.fsbox.lf.pane.1 config -bg #a18fff
      $dialog.fsbox.lf.pane.1.filelist config -bg #c1afff
      $dialog.fsbox.lf.pane.1.filelist.listbox config -bg #c1afff
      $dialog.fsbox.lf.pane.1.filelist.listbox config -selectbackground #ff92f4
      $dialog.fsbox.lf.pane.1.filelist.listbox config -highlightbackground #a18fff
      $dialog.fsbox.lf.pane.1.filelist.listbox config -highlightcolor #ff00ae
      $dialog.fsbox.lf.pane.1.filelist.hsb config -troughcolor blue
      $dialog.fsbox.lf.pane.1.filelist.hsb config -bg #a18fff
      $dialog.fsbox.lf.pane.1.filelist.hsb config -activebackground #ff00ae
      $dialog.fsbox.lf.pane.1.filelist.hsb config -highlightthickness 0
      $dialog.fsbox.lf.pane.1.filelist.vsb config -troughcolor blue
      $dialog.fsbox.lf.pane.1.filelist.vsb config -bg #a18fff
      $dialog.fsbox.lf.pane.1.filelist.vsb config -activebackground #ff00ae 
      $dialog.fsbox.lf.pane.1.filelist.vsb config -highlightthickness 0
      $dialog.fsbox.lf.pane.1.file.shell.slistbox.listbox config -bg #c1afff
      $dialog.fsbox.lf.pane.1.file.label config -bg #a18fff
      $dialog.fsbox.lf.pane.1.file.frame.arrow config -bg #816fff
      $dialog.fsbox.lf.pane.1.file.frame.arrow config -activebackground #ff00ae
      $dialog.fsbox.lf.pane.1.file.frame.arrow config -highlightthickness 0
      $dialog.fsbox.lf.pane.1.file.frame.entry config -bg #c1afff
      $dialog.fsbox.lf.pane.1.file.frame.entry config -highlightbackground #a18fff
      $dialog.fsbox.lf.pane.1.file.frame.entry config -highlightcolor #ff00ae
      $dialog.fsbox.lf.pane.2 config -bg #a18fff
      $dialog.fsbox.lf.pane.2.dirlist.hlist config -bg #c1afff
      $dialog.fsbox.lf.pane.2.dirlist.hlist config -selectbackground #ff92f4
      $dialog.fsbox.lf.pane.2.dirlist.hlist config -highlightbackground #a18fff
      $dialog.fsbox.lf.pane.2.dirlist.hlist config -highlightcolor #ff00ae
      $dialog.fsbox.lf.pane.2.dirlist.hsb config -troughcolor blue
      $dialog.fsbox.lf.pane.2.dirlist.hsb config -bg #a18fff
      $dialog.fsbox.lf.pane.2.dirlist.hsb config -activebackground #ff00ae
      $dialog.fsbox.lf.pane.2.dirlist.hsb config -highlightthickness 0
      $dialog.fsbox.lf.pane.2.dirlist.vsb config -troughcolor blue
      $dialog.fsbox.lf.pane.2.dirlist.vsb config -bg #a18fff
      $dialog.fsbox.lf.pane.2.dirlist.vsb config -activebackground #ff00ae 
      $dialog.fsbox.lf.pane.2.dirlist.vsb config -highlightthickness 0
      $dialog.fsbox.lf.pane.2.dir.shell.slistbox.listbox config -bg #c1afff
      $dialog.fsbox.lf.pane.2.dir.label config -bg #a18fff
      $dialog.fsbox.lf.pane.2.dir.frame.arrow config -bg #816fff
      $dialog.fsbox.lf.pane.2.dir.frame.arrow config -activebackground #ff00ae
      $dialog.fsbox.lf.pane.2.dir.frame.arrow config -highlightthickness 0
      $dialog.fsbox.lf.pane.2.dir.frame.entry config -bg #c1afff
      $dialog.fsbox.lf.pane.2.dir.frame.entry config -highlightbackground #a18fff
      $dialog.fsbox.lf.pane.2.dir.frame.entry config -highlightcolor #ff00ae
      $dialog.fsbox.lf.pane.sep1 config -width 3
      $dialog.fsbox.lf.pane.sep1 config -highlightthickness 0
      $dialog.fsbox.lf.pane config -separatorbg #ff5555
      $dialog.fsbox.lf.pane config -separatoractivebg red
      $dialog.fsbox.lf.pane config -handlebg #ff5555
      $dialog.fsbox.lf.pane config -handleactivebg red
      $dialog.fsbox.lf.types.label config -bg #a18fff
      $dialog.fsbox.lf.types.frame.arrow config -bg #816fff
      $dialog.fsbox.lf.types.frame.arrow config -activebackground #ff00ae
      $dialog.fsbox.lf.types.frame.arrow config -highlightthickness 0
      $dialog.fsbox.lf.types.frame.entry config -bg #c1afff
      $dialog.fsbox.lf.types.frame.entry config -highlightbackground #a18fff
      $dialog.fsbox.lf.types.frame.entry config -highlightcolor #ff00ae
      $dialog.fsbox.lf.types.shell.slistbox.listbox config -bg #c1afff
